# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
  - name: rdbms_post_patch | SID
    debug:
      msg:
        - "Running post patch operations for SID: {{ oracle_sid }}"

  - name: rdbms_post_patch | Upgrade database
    shell: |
      set -o pipefail
      echo "
      startup upgrade;
      " | sqlplus / as sysdba
    environment:
      ORACLE_HOME: "{{ oracle_home }}"
      ORACLE_SID: "{{ oracle_sid }}"
      PATH: "{{ oracle_home }}/bin:$PATH"
    register: upgrade_db
    become: yes
    become_user: "{{ oracle_user }}"
    when:
      - patch.upgrade
    tags: patch_rdbms,upgrade_db

  - name: rdbms_post_patch | upgrade output
    debug:
      msg:
        - "{{ upgrade_db }}"
    when:
      - patch.upgrade
    tags: patch_rdbms,upgrade_db

  - name: rdbms_post_patch | Start home
    shell: |
      {{ oracle_home }}/bin/srvctl start home -o {{ oracle_home }} -s {{ swlib_unzip_path }}/db_state.out
    environment:
      ORACLE_HOME: "{{ oracle_home }}"
    register: start_home
    failed_when: start_home.rc not in [0,2]
    become: yes
    become_user: "{{ oracle_user }}"
    tags: patch_rdbms,start_home

  - name: rdbms_post_patch | Start database
    command: "{{ oracle_home }}/bin/srvctl start database -db {{ db_name }}"
    environment:
      ORACLE_HOME: "{{ oracle_home }}"
    register: start_db
    failed_when: start_db.rc not in [0,2]
    become: yes
    become_user: "{{ oracle_user }}"
    when:
      - not patch.upgrade
    tags: patch_rdbms,start_db

  - name: rdbms_post_patch | Start database output
    debug:
      msg:
        - "{{ start_db }}"

  - name: rdbms_post_patch | Upgrade PDB
    shell: |
      set -o pipefail
      echo "
      alter pluggable database all open upgrade;
      " | sqlplus / as sysdba
    environment:
      ORACLE_HOME: "{{ oracle_home }}"
      ORACLE_SID: "{{ oracle_sid }}"
      PATH: "{{ oracle_home }}/bin:$PATH"
    register: upgrade_pdb
    become: yes
    become_user: "{{ oracle_user }}"
    when:
      - patch.upgrade
      - oracle_ver != '11.2.0.4.0'
    tags: patch_rdbms,start_pdb

  - name: rdbms_post_patch | upgrade pdb output
    debug:
      msg:
        - "{{ upgrade_pdb }}"
    when:
      - patch.upgrade
      - oracle_ver != '11.2.0.4.0'

  #- name: DB post patch | Start database
  #  #command: "{{ oracle_home }}/bin/srvctl start database -db {{ item.1 }}"
  #  command: "{{ oracle_home }}/bin/srvctl start database -db {{ db_name }}"
  #  environment:
  #    ORACLE_HOME: "{{ oracle_home }}"
  #  register: start_db
  #  failed_when: start_db.rc not in [0,2]
  #  become: yes
  #  become_user: "{{ oracle_user }}"
  #  when: 
  #    - not patch.upgrade
  #  tags: patch_rdbms,start_db

  - name: rdbms_post_patch | Start PDB
    shell: |
      set -o pipefail
      echo "
      alter pluggable database all open;
      " | sqlplus / as sysdba
    environment:
      ORACLE_HOME: "{{ oracle_home }}"
      ORACLE_SID: "{{ oracle_sid }}"
      PATH: "{{ oracle_home }}/bin:$PATH"
    become: yes
    become_user: "{{ oracle_user }}"
    tags: patch_rdbms,start_pdb

  - name: rdbms_post_patch | Run datapatch
    shell: |
      {{ oracle_home }}/OPatch/datapatch -verbose
    environment:
      ORACLE_SID: "{{ oracle_sid }}"
      ORACLE_HOME: "{{ oracle_home }}"
      PATH: "{{ oracle_home }}/bin:$PATH"
    register: datapatch
    failed_when: "datapatch.rc != 0"
    become: yes
    become_user: "{{ oracle_user }}"
    tags: patch_rdbms,datapatch

  - name: rdbms_post_patch | datapatch output
    debug:
      msg:
        - "{{ datapatch }}"

  - name: rdbms_post_patch  | Recompile invalid objects
    shell: |
      set -o pipefail
      echo "
      @?/rdbms/admin/utlrp;
      " | sqlplus / as sysdba
    environment:
      ORACLE_HOME: "{{ oracle_home }}"
      ORACLE_SID: "{{ oracle_sid }}"
      PATH: "{{ oracle_home }}/bin:$PATH"
    become: yes
    become_user: "{{ oracle_user }}"
    tags: patch_rdbms,utlrp

  - name: rdbms_post_patch | Patch registry
    shell: |
      set -o pipefail
      echo "
      set pages 0 lines 200
      col action_time for a28
      col action for a10
      col status for a10
      select action_time, action, status, patch_id from dba_registry_sqlpatch order by action_time;
      " | sqlplus -s / as sysdba
    environment:
      ORACLE_HOME: "{{ oracle_home }}"
      ORACLE_SID: "{{ oracle_sid }}"
      PATH: "{{ oracle_home }}/bin:$PATH"
    register: patch_registry
    become: yes
    become_user: "{{ oracle_user }}"
    tags: patch_rdbms

  - name: rdbms_post_patch | Patch registry
    debug:
      msg: "{{ patch_registry }}"
